
replica_count: 2
image: dockercloud/hello-world:latest
namespace: helloworld-ns2
containerPort: 3000

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30020

selector_labels:
  app: helloworldpod
  env: staging

env:
  LISTEN_PORT: 3000
  env: staging
