# Default values for helloworlproject.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replica_count: 1
image: dockercloud/hello-world:latest
namespace: helloworld-ns
containerPort: 3000


service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30010

selector_labels:
  app: helloworldpod
  env: dev
