apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  namespace: {{ .Values.namespace}}
spec:
  {{- if .Values.replica_count }}
  replicas: {{ .Values.replica_count }}
  {{- end }}
  selector:
    matchLabels:
      {{- range $key,$value := .Values.selector_labels}}
      {{ $key }}: {{ $value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key,$value := .Values.selector_labels}}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image}}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
          {{- range $key,$value := .Values.env}}
          - name: {{ $key }}
            value : {{ $value | quote }}
          {{- end }}
