# Default values for helloworlproject.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

min_replicas: 1
max_replicas: 6
image: dockercloud/hello-world:latest
namespace: helloworld-ns
containerPort: 3000

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30010

selector_labels:
  app: helloworldpod
  env: dev

env:
  LISTEN_PORT: 3000
  env: dev

resources:
  cpu: 20
  memory: 80

requests:
  memory: 128Mi
  cpu: 125m

limits:
  memory: 256Mi
  cpu: 250m