apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-scaler
spec:
  maxReplicas: {{ .Values.max_replicas }}
  minReplicas: {{ .Values.min_replicas }}
  metrics:
  {{- range $key,$value := .Values.resources}}
  - type: Resource
    resource:
      name: {{ $key }}
      target:
        type: Utilization
        averageUtilization: {{ $value }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-deploy
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 1
        periodSeconds: 10
